language: node_js
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
